In [1]:
import pandas as pd

In [2]:
churn_data = pd.read_csv('Data/churn_data.csv')
churn_data

,state,account length,area code,phone number,international plan,voice mail plan,number vmail messages,total day minutes,total day calls,total day charge,...,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge,customer service calls,churn
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,414-4276,no,yes,36,156.2,77,26.55,...,126,18.32,279.1,83,12.56,9.9,6,2.67,2,False
3329,WV,68,415,370-3271,no,no,0,231.1,57,39.29,...,55,13.04,191.3,123,8.61,9.6,4,2.59,3,False
3330,RI,28,510,328-8230,no,no,0,180.8,109,30.74,...,58,24.55,191.9,91,8.64,14.1,6,3.81,2,False
3331,CT,184,510,364-6381,yes,no,0,213.8,105,36.35,...,84,13.57,139.2,137,6.26,5.0,10,1.35,2,False
3332,TN,74,415,400-4344,no,yes,25,234.4,113,39.85,...,82,22.60,241.4,77,10.86,13.7,4,3.70,0,False

In [4]:
churn_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   state                   3333 non-null   object
 1   account length          3333 non-null   int64
 2   area code               3333 non-null   int64
 3   phone number            3333 non-null   object
 4   international plan      3333 non-null   object
 5   voice mail plan         3333 non-null   object
 6   number vmail messages   3333 non-null   int64
 7   total day minutes       3333 non-null   float64
 8   total day calls         3333 non-null   int64
 9   total day charge        3333 non-null   float64
 10  total eve minutes       3333 non-null   float64
 11  total eve calls         3333 non-null   int64
 12  total eve charge        3333 non-null   float64
 13  total night minutes     3333 non-null   float64
 14  total night calls       3333 non-null   int64
 15  total night charge      3333 non-null   float64
 16  total intl minutes      3333 non-null   float64
 17  total intl calls        3333 non-null   int64
 18  total intl charge       3333 non-null   float64
 19  customer service calls  3333 non-null   int64
 20  churn                   3333 non-null   bool
dtypes: bool(1), float64(8), int64(8), object(4)
memory usage: 524.2+ KB

In [3]:
for col in churn_data.columns:
    print(churn_data[col].value_counts())

WV    106
MN     84
NY     83
AL     80
OH     78
OR     78
WI     78
WY     77
VA     77
CT     74
VT     73
MI     73
ID     73
TX     72
UT     72
IN     71
MD     70
KS     70
MT     68
NC     68
NJ     68
CO     66
NV     66
WA     66
MA     65
MS     65
RI     65
AZ     64
MO     63
FL     63
ND     62
ME     62
NM     62
OK     61
DE     61
NE     61
SC     60
SD     60
KY     59
IL     58
NH     56
AR     55
DC     54
GA     54
TN     53
HI     53
AK     52
LA     51
PA     45
IA     44
CA     34
Name: state, dtype: int64
105    43
87     42
93     40
101    40
90     39
       ..
191     1
199     1
215     1
221     1
2       1
Name: account length, Length: 212, dtype: int64
415    1655
510     840
408     838
Name: area code, dtype: int64
330-6208    1
397-6425    1
396-2335    1
347-7420    1
333-2611    1
           ..
365-7784    1
422-4956    1
416-7679    1
401-4650    1
383-2017    1
Name: phone number, Length: 3333, dtype: int64
no     3010
yes     323
Name: international plan, dtype: int64
no     2411
yes     922
Name: voice mail plan, dtype: int64
0     2411
31      60
29      53
28      51
33      46
27      44
30      44
24      42
26      41
32      41
25      37
23      36
36      34
35      32
22      32
39      30
37      29
34      29
21      28
38      25
20      22
19      19
40      16
42      15
17      14
41      13
16      13
43       9
15       9
18       7
44       7
14       7
45       6
12       6
46       4
13       4
47       3
8        2
48       2
50       2
9        2
11       2
49       1
10       1
4        1
51       1
Name: number vmail messages, dtype: int64
174.5    8
159.5    8
154.0    8
175.4    7
162.3    7
        ..
199.9    1
105.8    1
125.6    1
179.8    1
270.8    1
Name: total day minutes, Length: 1667, dtype: int64
102    78
105    75
107    69
95     69
104    68
       ..
149     1
157     1
36      1
30      1
165     1
Name: total day calls, Length: 119, dtype: int64
27.12    8
26.18    8
29.67    8
31.18    7
27.59    7
        ..
19.36    1
16.95    1
34.12    1
48.35    1
13.28    1
Name: total day charge, Length: 1667, dtype: int64
169.9    9
230.9    7
209.4    7
201.0    7
220.6    7
        ..
335.0    1
258.9    1
134.7    1
318.8    1
317.2    1
Name: total eve minutes, Length: 1611, dtype: int64
105    80
94     79
108    71
97     70
102    70
       ..
45      1
49      1
145     1
153     1
0       1
Name: total eve calls, Length: 123, dtype: int64
14.25    11
16.12    11
15.90    10
18.62     9
14.44     9
         ..
12.64     1
13.83     1
11.39     1
28.03     1
20.53     1
Name: total eve charge, Length: 1440, dtype: int64
210.0    8
214.6    8
197.4    8
191.4    8
188.2    8
        ..
132.3    1
306.2    1
293.5    1
271.7    1
182.6    1
Name: total night minutes, Length: 1591, dtype: int64
105    84
104    78
91     76
102    72
100    69
       ..
164     1
166     1
33      1
149     1
36      1
Name: total night calls, Length: 120, dtype: int64
9.66     15
9.45     15
8.88     14
8.47     14
7.69     13
         ..
14.65     1
6.46      1
3.94      1
15.74     1
6.14      1
Name: total night charge, Length: 933, dtype: int64
10.0    62
11.3    59
9.8     56
10.9    56
10.1    53
        ..
18.9     1
1.3      1
2.7      1
2.6      1
3.1      1
Name: total intl minutes, Length: 162, dtype: int64
3     668
4     619
2     489
5     472
6     336
7     218
1     160
8     116
9     109
10     50
11     28
0      18
12     15
13     14
15      7
14      6
18      3
16      2
19      1
17      1
20      1
Name: total intl calls, dtype: int64
2.70    62
3.05    59
2.65    56
2.94    56
2.73    53
        ..
0.68     1
4.83     1
0.84     1
0.30     1
5.40     1
Name: total intl charge, Length: 162, dtype: int64
1    1181
2     759
0     697
3     429
4     166
5      66
6      22
7       9
9       2
8       2
Name: customer service calls, dtype: int64
False    2850
True      483
Name: churn, dtype: int64

In [5]:
churn_customers = churn_data[churn_data['churn'] == True]
churn_customers

,state,account length,area code,phone number,international plan,voice mail plan,number vmail messages,total day minutes,total day calls,total day charge,...,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge,customer service calls,churn
10,IN,65,415,329-6603,no,no,0,129.1,137,21.95,...,83,19.42,208.8,111,9.40,12.7,6,3.43,4,True
15,NY,161,415,351-7269,no,no,0,332.9,67,56.59,...,97,27.01,160.6,128,7.23,5.4,9,1.46,4,True
21,CO,77,408,393-7984,no,no,0,62.4,89,10.61,...,121,14.44,209.6,64,9.43,5.7,6,1.54,5,True
33,AZ,12,408,360-1596,no,no,0,249.6,118,42.43,...,119,21.45,280.2,90,12.61,11.8,3,3.19,1,True
41,MD,135,408,383-6029,yes,yes,41,173.1,85,29.43,...,107,17.33,122.2,78,5.50,14.6,15,3.94,0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3301,CA,84,415,417-1488,no,no,0,280.0,113,47.60,...,90,17.19,156.8,103,7.06,10.4,4,2.81,0,True
3304,IL,71,510,330-7137,yes,no,0,186.1,114,31.64,...,140,16.88,206.5,80,9.29,13.8,5,3.73,4,True
3320,GA,122,510,411-5677,yes,no,0,140.0,101,23.80,...,77,16.69,120.1,133,5.40,9.7,4,2.62,4,True
3322,MD,62,408,409-1856,no,no,0,321.1,105,54.59,...,122,22.57,180.5,72,8.12,11.5,2,3.11,4,True
3323,IN,117,415,362-5899,no,no,0,118.4,126,20.13,...,97,21.19,227.0,56,10.22,13.6,3,3.67,5,True

In [6]:
for col in churn_customers.columns:
    print(churn_customers[col].value_counts())

NJ    18
TX    18
MD    17
MI    16
MN    15
NY    15
SC    14
MS    14
WA    14
MT    14
NV    14
KS    13
ME    13
CT    12
MA    11
AR    11
OR    11
NC    11
UT    10
OH    10
WV    10
ID     9
CO     9
WY     9
CA     9
OK     9
NH     9
DE     9
IN     9
VT     8
PA     8
FL     8
AL     8
KY     8
SD     8
GA     8
MO     7
WI     7
ND     6
NM     6
RI     6
VA     5
NE     5
IL     5
TN     5
DC     5
LA     4
AZ     4
AK     3
HI     3
IA     3
Name: state, dtype: int64
105    9
119    9
93     8
76     8
113    8
      ..
140    1
114    1
104    1
224    1
1      1
Name: account length, Length: 164, dtype: int64
415    236
510    125
408    122
Name: area code, dtype: int64
387-1116    1
388-9285    1
345-4589    1
352-5466    1
405-5403    1
           ..
345-3947    1
380-7816    1
400-7002    1
379-7215    1
355-3801    1
Name: phone number, Length: 483, dtype: int64
no     346
yes    137
Name: international plan, dtype: int64
no     403
yes     80
Name: voice mail plan, dtype: int64
0     403
29      8
28      6
26      6
33      6
32      6
31      5
42      4
36      4
35      4
41      3
27      3
18      2
20      2
21      2
22      2
30      2
34      2
37      2
44      2
45      1
24      1
38      1
40      1
19      1
17      1
16      1
15      1
48      1
Name: number vmail messages, dtype: int64
133.3    2
157.8    2
278.0    2
271.1    2
145.0    2
        ..
226.3    1
229.7    1
261.4    1
158.4    1
151.0    1
Name: total day minutes, Length: 446, dtype: int64
106    16
108    14
120    12
103    12
89     11
       ..
143     1
144     1
145     1
148     1
0       1
Name: total day calls, Length: 98, dtype: int64
40.75    2
42.48    2
44.10    2
42.47    2
40.15    2
        ..
34.68    1
50.32    1
37.81    1
37.06    1
33.75    1
Name: total day charge, Length: 446, dtype: int64
209.4    3
205.7    3
226.1    3
211.3    3
218.1    2
        ..
263.5    1
312.5    1
249.4    1
267.1    1
228.5    1
Name: total eve minutes, Length: 428, dtype: int64
94     16
102    14
110    13
117    12
88     11
       ..
69      1
137     1
76      1
129     1
168     1
Name: total eve calls, Length: 90, dtype: int64
17.71    4
20.09    3
17.80    3
14.20    3
17.48    3
        ..
15.80    1
14.67    1
30.91    1
14.39    1
11.00    1
Name: total eve charge, Length: 411, dtype: int64
214.2    4
197.4    3
178.1    3
227.0    3
255.3    3
        ..
165.7    1
230.7    1
224.3    1
156.8    1
173.0    1
Name: total night minutes, Length: 420, dtype: int64
106    14
100    13
76     11
98     11
78     11
       ..
146     1
147     1
148     1
151     1
49      1
Name: total night calls, Length: 96, dtype: int64
9.40     5
8.01     5
9.64     5
10.22    4
8.88     4
        ..
5.32     1
8.82     1
13.14    1
11.39    1
5.80     1
Name: total night charge, Length: 346, dtype: int64
13.9    11
10.3    10
11.1    10
8.8     10
11.0    10
        ..
14.6     1
4.3      1
16.4     1
17.9     1
5.5      1
Name: total intl minutes, Length: 119, dtype: int64
2     108
3      98
4      79
5      53
6      43
1      31
7      27
9      14
8      11
10      8
11      4
15      3
20      1
14      1
13      1
12      1
Name: total intl calls, dtype: int64
3.75    11
2.78    10
3.00    10
2.38    10
2.97    10
        ..
4.19     1
5.40     1
1.46     1
1.27     1
1.65     1
Name: total intl charge, Length: 119, dtype: int64
1    122
0     92
2     87
4     76
3     44
5     40
6     14
7      5
9      2
8      1
Name: customer service calls, dtype: int64
True    483
Name: churn, dtype: int64